### ISSUE TITLE
Вопрос по функционалу

### ISSUE THREAD

**Issue by yanislav-igonin** [monke-systems/turbo-cli#1]
Денег мне нагенерить может?
![image](https://user-images.githubusercontent.com/15846431/186690636-01e07961-7925-4369-8fcb-3be4501351be.png)

**Comment by yanislav-igonin** [comment]
Добавишь?

**Comment by Enity** [comment]
> Добавишь?

Уже давно в релизе, при запуске CLI выбери команду "Who am i?" и следуй инструкциям.

**Comment by yanislav-igonin** [comment]
принял-понял
